server:
  # bind to platform-supplied PORT if present, otherwise default to 8080
  port: ${PORT:8080}

spring:
  datasource:
    # build a proper JDBC URL from env vars Railway provides
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
